import { ProviderProfile, Availability, Booking } from '../models/index.js';
const minOf=t=>{const [h,m]=String(t||'').split(':').map(Number);return h*60+m;};
const preferredWindow=t=>({MORNING:[480,720],AFTERNOON:[720,960],EVENING:[960,1200]})[String(t||'').toUpperCase()];
export async function matchProviders({category,requiredSkills=[],location='',preferredDate='',preferredTime=''}) {
 const profiles=await ProviderProfile.find({verificationStatus:'VERIFIED'}).select('-documents').populate('user','name profileImage');
 const ids=profiles.map(p=>p.user?._id).filter(Boolean),today=new Date().toISOString().slice(0,10);
 const [slots,activeBookings]=await Promise.all([Availability.find({provider:{$in:ids},isBooked:false,date:preferredDate||{$gte:today}}).select('provider date startTime endTime'),Booking.find({provider:{$in:ids},status:{$nin:['CANCELLED','SERVICE_COMPLETED','CUSTOMER_CONFIRMED','REVIEWED']}}).select('provider')]);
 const loads=new Map();for(const b of activeBookings)loads.set(String(b.provider),(loads.get(String(b.provider))||0)+1);
 return profiles.map(p=>{const skills=p.skills||[],cats=p.serviceCategories||[],matched=requiredSkills.filter(s=>skills.some(x=>x.toLowerCase()===s.toLowerCase())).length;const skillScore=requiredSkills.length?matched/requiredSkills.length:0.6;const categoryScore=cats.some(c=>c.toLowerCase()===String(category).toLowerCase())?1:0;const areaScore=(p.serviceAreas||[]).some(a=>location.toLowerCase().includes(a.toLowerCase())||a.toLowerCase().includes(location.toLowerCase()))?1:0.7;const openSlots=slots.filter(s=>String(s.provider)===String(p.user._id));const window=preferredWindow(preferredTime);const dateSlots=preferredDate?openSlots.filter(s=>s.date===preferredDate):openSlots;const timeSlots=window?dateSlots.filter(s=>minOf(s.startTime)<window[1]&&minOf(s.endTime)>window[0]):dateSlots;const available=timeSlots.length>0,availabilityScore=preferredDate||preferredTime?(available?1:0):(dateSlots.length?1:0.45);const workload=loads.get(String(p.user._id))||0,capacityScore=Math.max(0,1-workload/8);const availabilityWeighted=availabilityScore*.75+capacityScore*.25;const ratingScore=Math.min((p.rating||4)/5,1),expScore=Math.min((p.experience||1)/10,1),jobsScore=Math.min((p.completedJobs||0)/100,1);const score=Math.round((skillScore*.35+categoryScore*.2+areaScore*.15+availabilityWeighted*.15+ratingScore*.07+expScore*.05+jobsScore*.03)*100);const reasons=[matched?'Required skills match':'Related service skills',categoryScore?'Category match':'Can handle related work',areaScore===1?'Serves your area':'Nearby service coverage',available?'Available in the requested window':'Schedule to confirm',`${workload} active jobs`,`${(p.rating||4).toFixed(1)} rating · ${p.experience||1} years experience`];return{provider:p.user,profile:p,matchScore:score,available,reasons,estimatedRange:p.pricing};}).sort((a,b)=>b.matchScore-a.matchScore);
}
