import 'dotenv/config';import mongoose from 'mongoose';import bcrypt from 'bcryptjs';import{User,ProviderProfile,ServiceCategory,Skill,Availability,ServiceRequest,Quote,Booking,Invoice,Review,Dispute,Notification,PricingRule,MaintenanceReminder}from'../models/index.js';
if(!process.env.MONGO_URI)throw new Error('Set MONGO_URI before seeding.');await mongoose.connect(process.env.MONGO_URI);
const password=await bcrypt.hash('ServiSync@2026',12),roles=[['admin@servisync.demo','Platform Admin','PLATFORM_ADMIN'],['operations@servisync.demo','Operations Manager','OPERATIONS_MANAGER'],['support@servisync.demo','Support Agent','SUPPORT_AGENT'],['customer@servisync.demo','Ananya Rao','CUSTOMER'],['customer2@servisync.demo','Kabir Shah','CUSTOMER'],['customer3@servisync.demo','Mira Nair','CUSTOMER'],['customer4@servisync.demo','Ishaan Kapoor','CUSTOMER'],['customer5@servisync.demo','Tara Bose','CUSTOMER'],['customer6@servisync.demo','Rohan Shah','CUSTOMER'],['provider@servisync.demo','Ravi Kumar','SERVICE_PROVIDER'],['provider2@servisync.demo','Meera Iyer','SERVICE_PROVIDER'],['provider3@servisync.demo','Arjun Das','SERVICE_PROVIDER'],['provider4@servisync.demo','Nisha Patel','SERVICE_PROVIDER'],['provider5@servisync.demo','Dev Menon','SERVICE_PROVIDER']];
const users={};for(const[email,name,role]of roles)users[email]=await User.findOneAndUpdate({email},{email,name,role,password,isActive:true,address:'Bengaluru',phone:'+91 90000 00000'},{upsert:true,new:true,setDefaultsOnInsert:true});
const data=[['Plumbing','Leaks, pipes and fixtures','Leak Detection|Pipe Repair',450],['Electrical','Lighting, wiring and electrical safety','Electrical Repair|Safety Inspection',500],['Cleaning','Reliable help for a fresher home','Home Cleaning|Deep Cleaning',600],['AC Repair','Cooling, servicing and leak checks','AC Servicing|Leak Detection',600],['Appliance Repair','Repairs for everyday appliances','Appliance Diagnostics|Washing Machine Repair',500],['Carpentry','Furniture, fittings and woodwork','Furniture Repair|Door Repair',450],['Painting','Thoughtful interior refreshes','Interior Painting|Wall Preparation',800],['General Maintenance','Small fixes around the home','Home Maintenance',400]];
for(const[name,description,skillList,basePrice]of data){await ServiceCategory.findOneAndUpdate({name},{name,description,icon:name,skills:skillList.split('|'),basePrice,isActive:true},{upsert:true,new:true});await PricingRule.findOneAndUpdate({category:name},{name:`${name} standard pricing`,category:name,basePrice,minimumCharge:basePrice,platformFeePercent:5,isActive:true},{upsert:true,new:true});for(const skill of skillList.split('|'))await Skill.findOneAndUpdate({name:skill},{name:skill,category:name,isActive:true},{upsert:true});}
const pros=[['provider@servisync.demo',['Plumbing','AC Repair'],['Leak Detection','Pipe Repair','AC Servicing'],7,4.8],['provider2@servisync.demo',['Electrical','General Maintenance'],['Electrical Repair','Safety Inspection','Home Maintenance'],9,4.9],['provider3@servisync.demo',['Cleaning','Painting'],['Home Cleaning','Deep Cleaning','Interior Painting'],5,4.7],['provider4@servisync.demo',['Appliance Repair','Plumbing'],['Appliance Diagnostics','Washing Machine Repair','Leak Detection'],6,4.6],['provider5@servisync.demo',['Carpentry','General Maintenance','AC Repair'],['Furniture Repair','Door Repair','Home Maintenance','AC Servicing'],8,4.9]];
for(const[email,categories,skills,experience,rating]of pros){const user=users[email];await ProviderProfile.findOneAndUpdate({user:user._id},{user:user._id,serviceCategories:categories,skills,experience,bio:'Friendly, experienced home service professional serving Bengaluru.',serviceAreas:['Bengaluru','Indiranagar','Koramangala','Whitefield'],pricing:{min:400,max:1600},verificationStatus:'VERIFIED',rating,completedJobs:14,totalJobs:16},{upsert:true,new:true});for(let dayOffset=1;dayOffset<=14;dayOffset++){const date=new Date();date.setDate(date.getDate()+dayOffset);const dateKey=date.toISOString().slice(0,10);await Availability.findOneAndUpdate({provider:user._id,date:dateKey,startTime:'09:00',endTime:'17:00'},{provider:user._id,date:dateKey,startTime:'09:00',endTime:'17:00',isBooked:false},{upsert:true});}}
const customer=users['customer@servisync.demo'];let request=await ServiceRequest.findOne({customer,description:/AC is running/});if(!request)request=await ServiceRequest.create({customer,title:'AC is running but the room is not cooling',description:'My AC is running but the room is not cooling and water is leaking from the indoor unit.',category:'AC Repair',requiredSkills:['AC Servicing','Leak Detection'],location:'Indiranagar, Bengaluru',urgency:'MEDIUM',preferredDate:'2026-09-26',preferredTime:'Morning',aiAnalysis:{category:'AC Repair',requiredSkills:['AC Servicing','Leak Detection'],priority:'MEDIUM',shortSummary:'Your description appears to require AC repair assistance.',assisted:true},status:'QUOTES_AVAILABLE'});
const provider=users['provider@servisync.demo'];if(!await Quote.exists({request,provider}))await Quote.create({request,provider,amount:650,estimatedDuration:'About 90 minutes',message:'I can inspect the indoor unit, check the drain line and restore cooling.',status:'PENDING'});
const historyRequest=await ServiceRequest.findOneAndUpdate({customer:users['customer2@servisync.demo']._id,title:'Bedroom light keeps flickering'},{customer:users['customer2@servisync.demo']._id,title:'Bedroom light keeps flickering',description:'The bedroom light flickers when switched on.',category:'Electrical',requiredSkills:['Electrical Repair','Safety Inspection'],location:'Koramangala, Bengaluru',urgency:'LOW',status:'CUSTOMER_CONFIRMED'},{upsert:true,new:true});
const historyQuote=await Quote.findOneAndUpdate({request:historyRequest._id,provider:users['provider2@servisync.demo']._id},{request:historyRequest._id,provider:users['provider2@servisync.demo']._id,amount:550,estimatedDuration:'About 1 hour',message:'I can check the fixture and wiring safely.',status:'ACCEPTED'},{upsert:true,new:true});
const historyBooking=await Booking.findOneAndUpdate({request:historyRequest._id},{request:historyRequest._id,customer:historyRequest.customer,provider:users['provider2@servisync.demo']._id,quote:historyQuote._id,scheduledDate:'2026-08-14',startTime:'10:00',endTime:'11:00',status:'REVIEWED',completionConfirmed:true,notes:'Replaced a worn lamp holder and checked the connection.'},{upsert:true,new:true});
await Invoice.findOneAndUpdate({booking:historyBooking._id},{booking:historyBooking._id,serviceCharge:550,partsCost:80,platformFee:28,totalAmount:658,paymentStatus:'PAID'},{upsert:true,new:true});
await Review.findOneAndUpdate({booking:historyBooking._id},{booking:historyBooking._id,customer:historyBooking.customer,provider:historyBooking.provider,rating:5,comment:'Clear communication and careful work.'},{upsert:true,new:true});
const acBase=new Date();acBase.setMonth(acBase.getMonth()-6);const acDate=acBase.toISOString().slice(0,10);const acRequest=await ServiceRequest.findOneAndUpdate({customer:customer._id,title:'Spring AC servicing'},{customer:customer._id,title:'Spring AC servicing',description:'The AC received a routine spring service and filter clean.',category:'AC Repair',requiredSkills:['AC Servicing'],location:'Indiranagar, Bengaluru',urgency:'LOW',status:'REVIEWED'},{upsert:true,new:true});const acQuote=await Quote.findOneAndUpdate({request:acRequest._id,provider},{request:acRequest._id,provider,amount:600,estimatedDuration:'About 1 hour',message:'Routine coil, filter and drain check.',status:'ACCEPTED'},{upsert:true,new:true});const acBooking=await Booking.findOneAndUpdate({request:acRequest._id},{request:acRequest._id,customer:customer._id,provider,quote:acQuote._id,scheduledDate:acDate,startTime:'10:00',endTime:'11:00',status:'REVIEWED',completionConfirmed:true,notes:'Cleaned filters and checked the condensate drain.'},{upsert:true,new:true});await Invoice.findOneAndUpdate({booking:acBooking._id},{booking:acBooking._id,serviceCharge:600,partsCost:0,platformFee:30,totalAmount:630,paymentStatus:'PAID'},{upsert:true,new:true});await Review.findOneAndUpdate({booking:acBooking._id},{booking:acBooking._id,customer:customer._id,provider,rating:5,comment:'Routine AC service completed on time.'},{upsert:true,new:true});const reminderDue=new Date(acDate+'T12:00:00Z');reminderDue.setUTCMonth(reminderDue.getUTCMonth()+6);await MaintenanceReminder.findOneAndUpdate({booking:acBooking._id},{customer:customer._id,booking:acBooking._id,category:'AC Repair',title:'Time to check your AC repair service',suggestion:'It has been about six months since this AC service. Consider booking a maintenance check.',dueDate:reminderDue},{upsert:true,new:true});
const disputeRequest=await ServiceRequest.findOneAndUpdate({customer:users['customer3@servisync.demo']._id,title:'Tap is dripping'},{customer:users['customer3@servisync.demo']._id,title:'Tap is dripping',description:'The kitchen tap continues to drip after closing.',category:'Plumbing',requiredSkills:['Leak Detection','Pipe Repair'],location:'Whitefield, Bengaluru',urgency:'MEDIUM',status:'DISPUTED'},{upsert:true,new:true});
const disputeQuote=await Quote.findOneAndUpdate({request:disputeRequest._id,provider},{request:disputeRequest._id,provider,amount:450,estimatedDuration:'About 1 hour',message:'I can inspect the tap and seals.',status:'ACCEPTED'},{upsert:true,new:true});
const disputeBooking=await Booking.findOneAndUpdate({request:disputeRequest._id},{request:disputeRequest._id,customer:disputeRequest.customer,provider,quote:disputeQuote._id,scheduledDate:'2026-09-20',startTime:'14:00',endTime:'15:00',status:'DISPUTED',notes:'Customer requested support follow up.'},{upsert:true,new:true});
await Dispute.findOneAndUpdate({booking:disputeBooking._id},{booking:disputeBooking._id,customer:disputeBooking.customer,provider,reason:'Incomplete service',description:'The customer reported that the issue may need a follow up visit.',status:'OPEN'},{upsert:true,new:true});
await Notification.findOneAndUpdate({recipient:customer,title:'Welcome to ServiSync'},{recipient:customer,title:'Welcome to ServiSync',message:'Your home service journey starts here. Tell us what needs attention.',type:'INFO'},{upsert:true});
await Notification.findOneAndUpdate({recipient:provider,title:'Your profile is ready'},{recipient:provider,title:'Your profile is ready',message:'Your demo provider profile is verified and ready for requests.',type:'INFO'},{upsert:true});
console.log('ServiSync demo data is ready. Demo password: ServiSync@2026');await mongoose.disconnect();
