import React,{useCallback,useEffect,useState}from'react';
import{Search,Users,ShieldCheck,Tags,Wrench,Receipt,ShieldAlert,ClipboardList,BarChart3,Plus,Save,Check,Pause,RotateCcw}from'lucide-react';
import api from'../services/api';
import{Shell}from'./pages.jsx';

const tabs=[['analytics','Analytics',BarChart3],['users','Users',Users],['providers','Providers',ShieldCheck],['categories','Categories',Tags],['skills','Skills',Wrench],['pricing','Pricing rules',Receipt],['disputes','Disputes',ShieldAlert],['audit','Audit log',ClipboardList]];
const roles=['CUSTOMER','SERVICE_PROVIDER','OPERATIONS_MANAGER','SUPPORT_AGENT','PLATFORM_ADMIN'];
function PageHead({title,copy,children}){return <><div className="page-heading"><div><div className="eyebrow">PLATFORM ADMINISTRATION</div><h1>{title}</h1><p>{copy}</p></div>{children}</div></>}
function Notice({error,success}){return <>{error&&<div className="error-box">{error}</div>}{success&&<div className="success-box">{success}</div>}</>}
function Metric({label,value}){return <div className="panel"><small className="muted">{label}</small><h2>{value??'—'}</h2></div>}
function EditRow({item,fields,onSave,onToggle}){const[value,setValue]=useState({...item});return <div className="panel admin-record"><div className="admin-record-main"><strong>{item.name||item.category||item.title||item.user?.name||item._id}</strong><small>{item.email||item.user?.email||item.description||item.category}</small></div><details><summary>Edit</summary><div className="admin-form-grid">{fields.map(([key,label,type='text'])=><label key={key}>{label}<input type={type} value={Array.isArray(value[key])?value[key].join(', '):value[key]??''} onChange={e=>setValue({...value,[key]:key==='skills'?e.target.value.split(',').map(x=>x.trim()).filter(Boolean):type==='number'?Number(e.target.value):e.target.value})}/></label>)}</div><label className="check-row"><input type="checkbox" checked={value.isActive!==false} onChange={e=>setValue({...value,isActive:e.target.checked})}/> Active</label><button className="button button-dark button-small" onClick={()=>onSave(Object.fromEntries([...fields.map(([key])=>[key,value[key]]),['isActive',value.isActive!==false]]))}><Save size={14}/> Save</button></details>{onToggle}</div>}
export default function AdminConsole(){const[tab,setTab]=useState('analytics'),[data,setData]=useState([]),[summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[filter,setFilter]=useState({}),[form,setForm]=useState({});
 const load=useCallback(async()=>{setLoading(true);setError('');try{const routes={analytics:['/admin/overview','/admin/analytics'],users:['/admin/users'],providers:['/admin/providers'],categories:['/categories'],skills:['/admin/skills'],pricing:['/admin/pricing'],disputes:['/admin/disputes'],audit:['/admin/audit-logs']};const values=await Promise.all(routes[tab].map(route=>api.get(route)));if(tab==='analytics'){setSummary({...values[0],...values[1]});setData([])}else{setSummary(null);setData(Array.isArray(values[0])?values[0]:[]);}}catch(e){setError(e.message)}finally{setLoading(false)}},[tab]);
 useEffect(()=>{load()},[load]);
 async function save(path,method,body,message){try{await api[method](path,body);setSuccess(message);setError('');await load()}catch(e){setError(e.message);setSuccess('')}}
 const query=(field,value)=>{setFilter({...filter,[field]:value});};
 const filtered=data.filter(x=>{const role=filter.role?x.role===filter.role:true,status=filter.status?(x.verificationStatus||x.status)===filter.status:true,active=filter.active?String(x.isActive)===filter.active:true,search=filter.search?JSON.stringify(x).toLowerCase().includes(filter.search.toLowerCase()):true;return role&&status&&active&&search;});
 return <Shell active="Admin & analytics"><PageHead title={tabs.find(x=>x[0]===tab)?.[1]} copy="Manage the platform using live account, service, and booking data."><button className="button button-light button-small" onClick={load}><RotateCcw size={14}/> Refresh</button></PageHead><nav className="admin-tabs">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setFilter({});setSuccess('')}}><Icon size={15}/>{label}</button>)}</nav><Notice error={error} success={success}/>{loading?<div className="loading">Loading platform data…</div>:<>
 {tab==='analytics'&&summary&&<div className="admin-console-content"><div className="stats-grid"><Metric label="Total bookings" value={summary.total??summary.bookings}/><Metric label="Completed" value={summary.completed}/><Metric label="Cancelled" value={summary.cancelled}/><Metric label="Active providers" value={summary.activeProviders??summary.providers}/><Metric label="Open disputes" value={summary.openDisputes??summary.disputes}/><Metric label="Revenue" value={`₹${summary.revenue||0}`}/></div><div className="admin-grid"><section className="panel"><h2>Bookings by month</h2>{(summary.months||[]).map(x=><div className="bar-row" key={x._id}><span>{x._id}</span><div><i style={{width:`${Math.min(100,x.count*10)}%`}}/></div><b>{x.count}</b></div>)}</section><section className="panel"><h2>Services by category</h2>{(summary.servicesByCategory||[]).map(x=><div className="bar-row" key={x._id}><span>{x._id||'Uncategorised'}</span><div><i style={{width:`${Math.min(100,x.count*10)}%`}}/></div><b>{x.count}</b></div>)}</section><section className="panel"><h2>Booking status distribution</h2>{(summary.bookingStatuses||[]).map(x=><div className="status-row" key={x._id}><span>{x._id}</span><b>{x.count}</b></div>)}</section><section className="panel"><h2>Provider performance</h2>{(summary.providerPerformance||[]).map(x=><div className="status-row" key={x.provider?._id}><span>{x.provider?.name||'Provider'} · {x.completed}/{x.bookings} complete</span><b>{x.rating.toFixed(1)} ★</b></div>)}</section></div></div>}
 {['users','providers','categories','skills','pricing'].includes(tab)&&<div className="admin-console-content"><div className="filter-bar"><Search size={16}/><input placeholder="Search records" value={filter.search||''} onChange={e=>query('search',e.target.value)}/>{tab==='users'&&<select value={filter.role||''} onChange={e=>query('role',e.target.value)}><option value="">All roles</option>{roles.map(r=><option key={r}>{r}</option>)}</select>}{tab==='users'&&<select value={filter.active||''} onChange={e=>query('active',e.target.value)}><option value="">All accounts</option><option value="true">Active</option><option value="false">Disabled</option></select>}{tab==='providers'&&<select value={filter.status||''} onChange={e=>query('status',e.target.value)}><option value="">All verification states</option>{['PENDING','VERIFIED','REJECTED','SUSPENDED'].map(s=><option key={s}>{s}</option>)}</select>}</div>
 {['categories','skills','pricing'].includes(tab)&&<form className="panel admin-create-form" onSubmit={async e=>{e.preventDefault();const route=tab==='categories'?'/admin/categories':tab==='skills'?'/admin/skills':'/admin/pricing';await save(route,'post',{...form,...(typeof form.skills==='string'?{skills:form.skills.split(',').map(x=>x.trim()).filter(Boolean)}:{})},`${tabs.find(x=>x[0]===tab)[1].slice(0,-1)} created.`);setForm({})}}><h2>Add {tab==='categories'?'category':tab==='skills'?'skill':'pricing rule'}</h2><div className="admin-form-grid">{(tab==='categories'?[['name','Name'],['description','Description'],['skills','Skills (comma separated)'],['basePrice','Base price','number']]:tab==='skills'?[['name','Name'],['category','Category'],['description','Description']]:[['name','Rule name'],['category','Category'],['basePrice','Base price','number'],['minimumCharge','Minimum charge','number'],['platformFeePercent','Platform fee %','number']]).map(([key,label,type])=><label key={key}>{label}<input required={key==='name'||key==='category'} type={type||'text'} value={form[key]??''} onChange={e=>setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>)}</div><button className="button button-dark button-small"><Plus size={14}/> Create</button></form>}
 {filtered.map(item=>tab==='providers'?<div className="panel admin-record" key={item._id}><div className="admin-record-main"><strong>{item.user?.name}</strong><small>{item.user?.email} · {(item.serviceCategories||[]).join(', ')} · {item.rating?.toFixed(1)||'New'} ★</small></div><span className={`status status-${item.verificationStatus.toLowerCase()}`}>{item.verificationStatus}</span><div className="admin-actions">{['VERIFIED','REJECTED','SUSPENDED'].map(status=><button className="button button-light button-small" key={status} onClick={()=>save(`/admin/providers/${item._id}/verification`,'patch',{status},`Provider ${status.toLowerCase()}.`)}>{status==='VERIFIED'?<Check size={13}/>:<Pause size={13}/>} {status}</button>)}</div></div>:tab==='users'?<div className="panel admin-record" key={item._id}><div className="admin-record-main"><strong>{item.name}</strong><small>{item.email} · {item.role}</small></div><span className={`status ${item.isActive?'status-verified':'status-rejected'}`}>{item.isActive?'Active':'Disabled'}</span><button className="button button-light button-small" onClick={()=>save(`/admin/users/${item._id}`,'patch',{isActive:!item.isActive},`Account ${item.isActive?'disabled':'activated'}.`)}>{item.isActive?'Disable':'Activate'}</button></div>:tab==='categories'?<EditRow key={item._id} item={item} fields={ [['name','Name'],['description','Description'],['skills','Skills (comma separated)'],['basePrice','Base price','number']] } onSave={v=>save(`/admin/categories/${item._id}`,'patch',{...v,skills:Array.isArray(v.skills)?v.skills:String(v.skills||'').split(',').map(x=>x.trim()).filter(Boolean)},'Category updated.')}/>:tab==='skills'?<EditRow key={item._id} item={item} fields={ [['name','Name'],['category','Category'],['description','Description']] } onSave={v=>save(`/admin/skills/${item._id}`,'patch',v,'Skill updated.')}/>:<EditRow key={item._id} item={item} fields={ [['name','Rule name'],['category','Category'],['basePrice','Base price','number'],['minimumCharge','Minimum charge','number'],['platformFeePercent','Platform fee %','number']] } onSave={v=>save(`/admin/pricing/${item._id}`,'patch',v,'Pricing rule updated.')}/>)}{!filtered.length&&<div className="panel empty-state"><h3>No matching records</h3><p>Try another filter or add a record.</p></div>}</div>}
 {tab==='disputes'&&<div className="admin-console-content">{filtered.map(d=><div className="panel admin-record" key={d._id}><div className="admin-record-main"><strong>{d.reason} · {d.status}</strong><small>{d.customer?.name} · {d.provider?.name} · {d.description}</small></div><a className="button button-light button-small" href={`/support/disputes/${d._id}`}>Open details</a></div>)}{!filtered.length&&<div className="panel empty-state"><h3>No disputes</h3></div>}</div>}
 {tab==='audit'&&<div className="panel list-panel">{data.map(x=><div className="request-row" key={x._id}><span className="booking-info"><b>{x.action} · {x.entityType}</b><small>{x.actor?.name||'System'} · {x.description||x.entityId}</small></span><time>{new Date(x.createdAt).toLocaleString()}</time></div>)}{!data.length&&<div className="empty-state"><h3>No audit events yet</h3></div>}</div>}
 </>}</Shell>;
}
